// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {models} from '../models';
import {agent} from '../models';

export function GetConfig():Promise<config.AppConfig>;

export function GetFindings():Promise<Array<models.Finding>>;

export function GetSystemStatus():Promise<models.SystemStatus>;

export function ResetChat():Promise<void>;

export function SaveConfig(arg1:config.AppConfig):Promise<void>;

export function SendMessage(arg1:string):Promise<agent.ChatResponse>;
