// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SendMessage(arg1) {
    return window['go']['main']['App']['SendMessage'](arg1);
}

export function ResetChat() {
    return window['go']['main']['App']['ResetChat']();
}

export function GetSystemStatus() {
    return window['go']['main']['App']['GetSystemStatus']();
}

export function GetFindings() {
    return window['go']['main']['App']['GetFindings']();
}

export function GetConfig() {
    return window['go']['main']['App']['GetConfig']();
}

export function SaveConfig(arg1) {
    return window['go']['main']['App']['SaveConfig'](arg1);
}
