// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import type { ChatResponse, SystemStatus, Finding, AppConfig } from '../../../src/types/models';

export function SendMessage(message: string): Promise<ChatResponse>;

export function ResetChat(): Promise<void>;

export function GetSystemStatus(): Promise<SystemStatus>;

export function GetFindings(): Promise<Finding[]>;

export function GetConfig(): Promise<AppConfig>;

export function SaveConfig(config: AppConfig): Promise<void>;
